# Generated by Django 2.2.2 on 2019-06-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('memo', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Server_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='主机组')),
                ('memo', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Project', verbose_name='项目名称')),
            ],
            options={
                'db_table': 'server_group',
            },
        ),
        migrations.AddIndex(
            model_name='server_group',
            index=models.Index(fields=['name', 'project'], name='server_grou_name_86739c_idx'),
        ),
        migrations.AddIndex(
            model_name='server_group',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='server_group',
            unique_together={('name', 'project')},
        ),
    ]
